pennprojects/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'projects.views.index'),
    url(r'^projects/(?P<project_id>\d+)/$', 'projects.views.projectdisplay'),
    url(r'^submit/', 'projects.views.projectsubmit'),
    url(r'^about/', 'pennprojects.views.about'),
    url(r'^admin/', include(admin.site.urls)),
)

projects/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('projects.views',
    url(r'^$', 'index'),
    url(r'^(?P<project_id>\d+)/$', 'projectdisplay'),
)

projects/models.py
from django.db import models

APPROVAL = (
	(True, 'Approved'),
	(False, 'Pending approval'))

class Project(models.Model):
	name = models.CharField('project name', max_length=50)
	sub_date = models.DateTimeField('date submitted', editable=False)
	authors = models.TextField(max_length=100)
	demo_url = models.URLField(blank=True)
	description = models.TextField()
	album_url = models.URLField(blank=True)
	pitch = models.TextField(max_length=200)
	source_url = models.URLField(blank=True)
	thumbnail_url = models.URLField(blank=True)
	approved = models.BooleanField(choices=APPROVAL)

	def __unicode__(self):
		return self.name

projects/forms.py
from django.forms import ModelForm, ValidationError
from projects.models import Project
from django.utils.html import strip_tags

class ProjectForm(ModelForm):

    class Meta:
        model = Project
        exclude = ('approved', )

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['authors'].widget.attrs['rows'] = 3
        self.fields['description'].widget.attrs['rows'] = 10
        self.fields['pitch'].widget.attrs['rows'] = 3

    def clean(self):
        super(ProjectForm, self).clean()
        if 'album_url' in self.cleaned_data and self.cleaned_data['album_url']:
            if 'imgur.com/a/' not in self.cleaned_data['album_url']:
                raise ValidationError('Not a valid imgur album url')
        for k in self.cleaned_data.keys():
            self.cleaned_data[k] = strip_tags(self.cleaned_data[k])
        return self.cleaned_data

pennprojects/views.py
from django.shortcuts import render_to_response

def about(request):
    return render_to_response('about.html')

projects/views.py
from django.template import Context, loader
from projects.models import Project
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from projects.forms import ProjectForm

def index(request):
    latest_projects = Project.objects.all().order_by('-sub_date')
    approved_projects = []
    for project in latest_projects:
        if project.approved:
            approved_projects.append(project)
    paginator = Paginator(approved_projects, 20)
    page = request.GET.get('page')
    try:
        page_projects = paginator.page(page)
    except PageNotAnInteger:
        page_projects = paginator.page(1)
    except EmptyPage:
        page_projects = paginator.page(paginator.num_pages)

    t = loader.get_template('projects/index.html')
    c = Context({
        'page_projects': page_projects,
    })
    return HttpResponse(t.render(c))

def projectdisplay(request, project_id):
    p = get_object_or_404(Project, pk=project_id)
    return render_to_response('projects/projectdisplay.html', {'project': p})

def projectsubmit(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            pd = form.save(commit=False)
            pd.sub_date = timezone.now()
            pd.approved = False

            # format the authors list
            al = pd.authors.strip().replace('\r\n', '*').replace('\r', '*').replace('\n', '*').split('*')
            print al
            if len(al) > 1:
                al[-1] = 'and ' + al[-1].strip()

            if len(al) > 2:
                pd.authors = ', '.join(al)
            else:
                pd.authors = ' '.join(al)

            # make the thumbnail url a direct link if not already
            if pd.thumbnail_url:
                thumb = pd.thumbnail_url.strip()
                if 'imgur' in thumb and 'i.' not in thumb:
                    pd.thumbnail_url = 'i.' + thumb.replace('https://', '').replace('http://', '')
                if '.jpg' not in pd.thumbnail_url:
                    pd.thumbnail_url += '.jpg'

            pd.save()
            return render(request, 'projects/projectsubmit.html', {'submitted': True})
    else:
        form = ProjectForm()
    return render(request, 'projects/projectsubmit.html', {'form': form, 'submitted': False})

templates/about.html
<hmtl>
	<head>
		<meta charset="utf-8">
		<title>Penn Projects</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="A showcase for cool projects from the geeks at University of Pennsylvania.">
		<meta name="author" content="Ian Sibner">
		<link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
		<link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
		<link href="/static/css/style.css" rel="stylesheet">
		
			
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top">
		  <div class="navbar-inner">
			<div class="container-fluid">
			  <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
			  <a class="brand" href="/">Penn Projects</a>
			  <div class="nav-collapse collapse">
				<ul class="nav">
				  <li class="">
					<a href="/">Home</a>
				  </li>
				  <li class="active">
					<a href="/about">About DinPhil</a>
				  </li>
				  <li class="">
					<a href="/submit">Submit a Project</a>
				  </li>
				</ul>
			  </div>
			</div>
		  </div>
		</div>

		<div class="container-fluid">

	      <!-- Main hero unit for a primary marketing message or call to action -->
	      <div class="hero-unit">

	        <p>The Dining Philosophers are the University of Pennsylvania's Computer Science
	        interest group.  We hold events for the Computer Science department, including
	        guest lectures, faculty lunches, and social events.  One of our members sits in on the
	        faculty meetings to represent the undergraduate Computer Science body.  We also
	        host an annual programming contest for high school students called the
	        Philadelphia Classic.  It's also a great place to get to know other computer
	        science students and stay connected within the computer
	        science community at large.
	        </p>
	        <br />        <br />
	        <h2>Why are we called the Dining Philosophers?</h2>
	        <p>
	          Our name comes from a classic
	          computer science problem.  A group of
	          philosophers sit around a table with a plate in front of them and a chopstick
	          in between each person.  All the philosophers do is eat or think.  The
	          philosophers have to pick up chopsticks on each side to be
	          able to eat but they can only pick them up one at a time.  Once a philosopher
	          tries to eat, he won't put down a chopstick until he finishes eating.  This is
	          a classic case of a possible deadlock scenario.  If each philospher picks up
	          the chopstick to their left, then none of the philosophers will be able to eat
	          and since none of them will also put down the chopstick, all of them will be
	          stuck.  More information about this problem can be
	          found <a href="http://en.wikipedia.org/wiki/Dining_philosophers_problem">here</a>.
	        </p>
      </div>


		<script src="http://code.jquery.com/jquery-latest.js"> </script>
   	 	<script src="/static/bootstrap/js/bootstrap.min.js"> </script>
	</body>
</html>

templates/projects/about.html
<hmtl>
	<head>
		<meta charset="utf-8">
		<title>Penn Projects</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="A showcase for cool projects from the geeks at University of Pennsylvania.">
		<meta name="author" content="Ian Sibner">
		 <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
		 <link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
		 <link href="/static/css/style.css" rel="stylesheet">
		
			
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top">
		  <div class="navbar-inner">
			<div class="container-fluid">
			  <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
			  <a class="brand" href="/">Penn Projects</a>
			  <div class="nav-collapse collapse">
				<ul class="nav">
				  <li class="">
					<a href="/">Home</a>
				  </li>
				  <li class="">
					<a href="/about">About DinPhil</a>
				  </li>
				  <li class="active">
					<a href="/submit">Submit a Project</a>
				  </li>
				</ul>
			  </div>
			</div>
		  </div>
		</div>

		<div class="container-fluid">

	      <!-- Main hero unit for a primary marketing message or call to action -->
	      <div class="hero-unit">

	        <p>The Dining Philosophers are the University of Pennsylvania's Computer Science
	        interest group.  We hold events for the Computer Science department, including
	        guest lectures, faculty lunches, and social events.  One of our members sits in on the
	        faculty meetings to represent the undergraduate Computer Science body.  We also
	        host an annual programming contest for high school students called the
	        Philadelphia Classic.  It's also a great place to get to know other computer
	        science students and stay connected within the computer
	        science community at large.
	        </p>
	        <br />        <br />
	        <h2>Why are we called the Dining Philosophers?</h2>
	        <p>
	          Our name comes from a classic
	          computer science problem.  A group of
	          philosophers sit around a table with a plate in front of them and a chopstick
	          in between each person.  All the philosophers do is eat or think.  The
	          philosophers have to pick up chopsticks on each side to be
	          able to eat but they can only pick them up one at a time.  Once a philosopher
	          tries to eat, he won't put down a chopstick until he finishes eating.  This is
	          a classic case of a possible deadlock scenario.  If each philospher picks up
	          the chopstick to their left, then none of the philosophers will be able to eat
	          and since none of them will also put down the chopstick, all of them will be
	          stuck.  More information about this problem can be
	          found <a href="http://en.wikipedia.org/wiki/Dining_philosophers_problem">here</a>.
	        </p>
      </div>


		<script src="http://code.jquery.com/jquery-latest.js"> </script>
   	 	<script src="/static/bootstrap/js/bootstrap.min.js"> </script>
	</body>
</html>

templates/projects/index.html
<hmtl>
	<head>
		<meta charset="utf-8">
		<title>Penn Projects</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="A showcase for cool projects from the geeks at University of Pennsylvania.">
		<meta name="author" content="Ian Sibner">
		<link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
		<link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
		<link href="/static/css/style.css" rel="stylesheet">
		<link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon" >
		
			
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container-fluid">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</a>
					<div class="nav-collapse collapse">
					<a href="#" class="brand"><i class="icon-home icon-white"></i></a>
					<ul class="nav pull-right">
					  <li><a href="/about">About DinPhil</a></li>
					  <li><a href="/submit">Submit a Project</a></li>
					</ul>
					</div><!--/.nav-collapse -->
				</div>
			</div>
		</div>
		
				      <div class="hero-unit">
        <h1>Penn Projects:</h1>
        <blockquote class="tagline">a repository of cool projects and hacks built by the CIS@Penn community</blockquote>
      </div>
		
	<div class="pagination center">
	  <ul>
	  	<li>
		    {% if page_projects.has_previous %}
	            <a href="?page={{ page_projects.previous_page_number }}">«</a>
	        {% else %}
	        	<span class="current">«</span>
	        {% endif %}
	    </li>
	    {% for pagenum in page_projects.paginator.page_range %}
			{% if page_projects.number != pagenum %}
				<li><a href="?page={{ pagenum }}" style="text-decoration:underline">{{ pagenum }}</a></li>
			{% else %}
				<li><span class="current">{{ pagenum }}</span></li>
			{% endif %}
		{% endfor %}
		<li>
		    {% if page_projects.has_next %}
	            <a href="?page={{ page_projects.next_page_number }}">»</a>
	        {% else %}
	        	<span class="current">»</span>
	        {% endif %}
	    </li>
	  </ul>
	</div>
	<div id="picture_tiles">
		{% if page_projects %}
			{% for project in page_projects %}
				<a href = "/projects/{{ project.id }}/">
					<div class="tile">
						{% if project.thumbnail_url %}
						<img src="{{project.thumbnail_url}}"> <!--must be changed to cover photo reference-->
						{% else %}
						<img src="http://i.imgur.com/UowPi.gif">
						{% endif %}
						<div class="caption">
							<h5>{{ project.name }}</h5>
						</div>
					</div>
				</a>
			{% endfor %}
		{% else %}
			<h1>No projects are available.</h1>
		{% endif %}
		
	</div>

	<div class="navbar navbar-fixed-bottom">
		<div class="navbar-inner no-shadow">
			<div class="container-fluid">
				<span class="brand" id="footer">Created by <a href="http://www.tomshen.me/">Tom Shen</a> &amp; Ian Sibner</span>				
			</div>
		</div>
	</div>


		<script src="http://code.jquery.com/jquery-latest.js"> </script>
		<script src="/static/bootstrap/js/bootstrap.min.js"> </script>
		<script src="/static/bootstrap/js/jquery.masonry.js"> </script>
		<script type="text/javascript">
		$().ready(function(){
			var $container = $('#picture_tiles');
			$container.imagesLoaded(function(){
			  $container.masonry({
				itemSelector : '.tile',
				isAnimated: true,
				 animationOptions: {
					duration: 550,
					queue: true
				  },
				columnWidth: function( containerWidth ) {
					return containerWidth / 6;
				  }
			  });
			});
		});
		</script>
	</body>
</html>

templates/projects/projectdisplay.html
<hmtl>
	<head>
		<meta charset="utf-8">
	    <title>{{project.name}} - Penn Projects</title>
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <meta name="description" content="A showcase for cool projects from the geeks at University of Pennsylvania.">
	    <meta name="author" content="Ian Sibner">
	    <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
	    <link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
	    <link href="/static/css/style.css" rel="stylesheet">
	    <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon" >
	    
			
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top">
	      <div class="navbar-inner">
	        <div class="container-fluid">
	          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
          	  </a>
	          <a class="brand" href="/">Penn Projects</a>
	          <div class="nav-collapse collapse">
	            <ul class="nav">
	              <li class="">
	                <a href="/">Home</a>
	              </li>
	              <li class="">
	                <a href="/about">About DinPhil</a>
	              </li>
	              <li class="">
	                <a href="/submit">Submit a Project</a>
	              </li>
	            </ul>
	          </div>
	        </div>
	      </div>
	    </div>

		<div class = "container">
			<div class = "row-fluid">
				{% if project.source_url %}<a id ="project_source" class = "pull-right" href = "{{project.source_url}}"><img src = "http://i.imgur.com/UMB5c.png" height = "64px" width = "64px"></a>{% endif %}
				{% if project.demo_url %}<a class = "pull-right" href = "{{project.demo_url}}" ><button class="btn btn-large btn-primary" type="button" style = "padding : 5px 10px">View Demo</button></a>{% endif %}
				{% if project.name %}<h1>{{project.name}}</h1>{% endif %}

				<h3 id = "authors">{% if project.authors %}By {{project.authors}}. {% endif %}{% if project.sub_date %}Submitted {{project.sub_date}}{% endif %}</h3>
				{% if project.pitch %}<h3>{{project.pitch}}</h3>{% endif %}
				{% if project.description %}<h6 class = "description">{{project.description}}</h6>{% endif %}
				{% if project.album_url %}<iframe class="imgur-album" style = "" width="100%" height="550" frameborder = "0" src="{{project.album_url}}/embed"></iframe>{% endif %}
			</div>

		</div>


		<script src="http://code.jquery.com/jquery-latest.js"> </script>
   	 	<script src="/static/bootstrap/js/bootstrap.min.js"> </script>
	</body>
</html>

templates/projects/projectsubmit.html
<hmtl>
	<head>
		<meta charset="utf-8">
		<title>Penn Projects</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="A showcase for cool projects from the geeks at University of Pennsylvania.">
		<meta name="author" content="Ian Sibner">
		<link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
		<link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
		<link href="/static/css/style.css" rel="stylesheet">
		<link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon" >
			
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top">
		  <div class="navbar-inner">
			<div class="container-fluid">
			  <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
			  <a class="brand" href="/">Penn Projects</a>
			  <div class="nav-collapse collapse">
				<ul class="nav">
				  <li class="">
					<a href="/">Home</a>
				  </li>
				  <li class="">
					<a href="/about">About DinPhil</a>
				  </li>
				  <li class="active">
					<a href="/submit">Submit a Project</a>
				  </li>
				</ul>
			  </div>
			</div>
		  </div>
		</div>

		<div class = "container-fluid" id = "form">
			<div class = "row-fluid">
				{% if form.errors %}
					<p id="error-message">
						Please correct the error{{ form.errors|pluralize }} below.
					</p>
				{% endif %}

				<form action="" method="post" class ="span8 offset2">
					{% csrf_token %}
					{{ form.as_p }}
					<input type="submit" value="Submit">
				</form>
			</div>

		</div>


		<script src="http://code.jquery.com/jquery-latest.js"> </script>
   	 	<script src="/static/bootstrap/js/bootstrap.min.js"> </script>
		<script src="/static/bootstrap/js/jquery.autosize.js"> </script>
		{% if submitted %}
			<script src="/static/js/bootbox.min.js"> </script>
			<script type="text/javascript">
				$(document).ready(function(){
					bootbox.dialog("Project submission successful!", [{
					    "label" : "Submit another project",
					    "class" : "btn-success",
					    "callback": function() {
					        window.location.replace("/submit");
					    }
					}, {
					    "label" : "Penn Projects home",
					    "class" : "btn-danger",
					    "callback": function() {
					        window.location.replace("/");
					    }
					}, {
					    "label" : "GO DANCING!",
					    "class" : "btn-primary",
					    "callback": function() {
					        window.location.replace("http://www.youtube.com/watch?v=ZZ5LpwO-An4");
					    }
					}]);


				});
			</script>
		{% endif %}
		<script type="text/javascript">
			$(document).ready(function(){
			    $("textarea").autosize({append: "\n"});  
			    $("input").addClass("defaultText").addClass("defaultTextActive");
			    $("input").last().removeClass("defaultText").removeClass("defaultTextActive");
				$("textarea").addClass("defaultText").addClass("defaultTextActive");
			});
		</script>
		<script type="text/javascript">
		<!--
		$(document).ready(function()
		{

			var nameString = "e.g. My Really Awesome Project",
			authorString = "List each author on a new line",
			demoString = "e.g. myawesomesite.com", 
			descriptionString = "Tell the world what you did and how you did it.",
			albumString = "Upload your pictures to an album on imgur.com, then put the link here.",
			pitchString = "Give us an overview with a ten-second pitch.",
			sourceString = "e.g. github.com/tomshen/penn-projects/",
			thumbnailString = "Your project's preferred thumbnail- e.g. imgur.com/yourURL";
			//Jeez, I should have put these in an array... dat boilerplate...

			$("#id_name").attr({title:nameString});
			$("#id_authors").attr({title:authorString});
			$("#id_demo_url").attr({title:demoString});
			$("#id_description").attr({title:descriptionString});
			$("#id_album_url").attr({title:albumString});
			$("#id_pitch").attr({title:pitchString});
			$("#id_source_url").attr({title:sourceString});
			$("#id_thumbnail_url").attr({title:thumbnailString});



		    $(".defaultText").focus(function(srcc)
		    {
		        if ($(this).attr("placeholder") == $(this).attr("title"))
		        {
		            $(this).removeClass("defaultTextActive");
		            $(this).removeAttr("placeholder");
		        }
		    });
		    
		    $(".defaultText").blur(function()
		    {	
		    	var currentVal = $(this).val().trim();
		        if (currentVal == "")
		        {
		            $(this).addClass("defaultTextActive");
		            var titleString = $(this).attr("title");
		            $(this).attr("placeholder", titleString);
		        }
		        $(this).val(currentVal);//Trim value string
		    });
		    
		    $(".defaultText").blur();        
		});
		//-->
		</script>
	</body>
</html>